[env:planeradar-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

board_build.filesystem = littlefs

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^7.0.0
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer@^1.2.3

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -I include
    -DAPP_VERSION=\"0.0.0-dev\"
    -DOTA_VERSION_URL=\"https://NightStinks.github.io/PlaneRadar/version.json\"
